CREATE DATABASE IF NOT EXISTS mutezone;

CREATE TABLE User{
    id SERIAL PRIMARY KEY NOT NULL,
    username CHARACTER VARYING(200) NOT NULL UNIQUE,
    password CHARACTER VARYING(200) NOT NULL,
    email CHARACTER VARYING(200) NOT NULL UNIQUE,
    description CHARACTER VARYING(2000) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    last_login TIMESTAMP,
    admin BOOL NOT NULL,
}