version: '3'

services: 
    hush.mutezone:
        build: 
            dockerfile: Dockerfile
            context: ./amb_back

    nginx:
        restart: always
        build: 
            dockerfile: Dockerfile
            context: ./
            
    mutezone:
        build: 
            dockerfile: Dockerfile
            context: ./amb_front
