version: '3'

services: 
  hush.mutezone:
    build: 
      context: ./amb_back
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    container_name: amb_back
    hostname: hush
    # domainname: mutezone.site
    volumes:
      - ./target:/usr/target
    networks:
      - app-network

#  reverse_proxy:
#    image: nginx:alpine
#    restart: always
#    container_name: reverse_proxy
#    ports:
#      - "80:80"
#     #- "443:443"
#    networks:
#      - app-network
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#    certbot:
#      image: certbot/certbot

  mutezone:
    build:
      context: ./amb_front
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: amb_front
    depends_on: 
      - hush.mutezone
    # domainname: mutezone.site
    volumes:
      - ./amb_front:/usr/src/app/amb_front
      - /usr/src/app/amb_front/node_modules
    networks:
      - app-network
#
  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "9595:9595"
    networks: 
      - app-network
    
#      
#
networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local
