version: '3'

services: 
  hush.mutezone:
    build: 
      context: ./amb_back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: amb_back
    #hostname: hush
    #domainname: mutezone.site
    volumes:
      - ./target:/usr/target
    networks:
      - app-network      
#	
#
#  webserver_nginx:
#    image: nginx:alpine
#    restart: always
#    container_name: webserver_nginx
#    tty: true
#    ports: 
#      - "80:80"
#      - "443:443"
#            
  mutezone:
    build:
      context: ./amb_front
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: amb_front
    #domainname: mutezone.site
    volumes:
      - ./amb_front:/usr/src/app/amb_front
      - /usr/src/app/amb_front/node_modules
    networks:
      - app-network
#
  postgres:
    image: postgres:11-alpine
    restart: always
    environment: 
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
    ports: 
        - 5432:5432
    
#      
#
networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local