-- Your SQL goes here

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  username TEXT NOT NULL UNIQUE,
  password CHARACTER VARYING(2000) NOT NULL,
  email TEXT NOT NULL UNIQUE,
  description CHARACTER VARYING(2000),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  admin BOOL NOT NULL,
  salt CHARACTER VARYING(2000)
)