-- Your SQL goes here

CREATE TABLE tracks (
    id SERIAL PRIMARY KEY NOT NULL,
    user_id INTEGER NOT NULL REFERENCES users(id),
    uuid_fname VARCHAR(255) NOT NULL,
    title CHARACTER VARYING(255) NOT NULL,
    path CHARACTER VARYING(2000) NOT NULL,
    description CHARACTER VARYING(2000),
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    duration INTEGER DEFAULT 0,
    credits CHARACTER VARYING(2000) NOT NULL
)