name: Rust

on:
    push:
        branches: [ $default-branch ]
    pull_request:
        branches: [ $default-branch ]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Build
            uses: actions-rs/cargo@v1
            run:
                shell: bash 
                working-directory: ./amb_back
            with: 
                command: build
                args: --verbose
                
          - name: Run tests
            uses: actions-rs/cargo@v1
            run: 
                shell: bash
                working-directory: ./amb_back
            with:
                command: test
                args: --verbose
