on: [push]
name: build

defaults:
    run:
        working-directory: amb_back
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: amb_back
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: build
        uses: actions-rs/cargo@v1
        working-directory: amb_back
        with:
          command: build
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
