name: Rust

on:
    push:
        branches: [ $default-branch ]
        pull_request:
        branches: [ $default-branch ]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v2
          - name: Build
            run:
                shell: bash 
                working-directory: ./amb_back
                cargo build --verbose
          - name: Run tests
            run: 
                shell: bash
                working-directory: ./amb_back
                cargo test --verbose